import { IOrder } from "@/app/utils/type";

// export const dummyOrders: IOrder[] = [
//   {
//     order_detail: [{ selectedTooth: [12, 4], type: "crown" }],
//     _id: "64f1a2b3c4d5e6f7g8h9i0j",
//     category: "Crown",
//     patient_name: "John Doe",
//     clinic_name: "Smile Dental Clinic",
//     doctor_name: "Dr. Alice Johnson",
//     prod_name: "Porcelain Crown",
//     rx_date: "2025-12-01",
//     due_date: "2025-12-15",
//     doctor_instruction: "Ensure proper bite alignment",
//     gender: "Male",
//     age: 45,
//     isUrgent: true,
//     is_remake: false,
//     designedPath: "/designs/order1.png",
//     designerId: "designer123",
//     deliveryId: "delivery456",
//     shade: "A2",
//     status: "Pending",
//     isAccepted: false,
//     isMilled: false,
//     isScanned: true,
//     isDesigned: false,
//     isDelivered: false,
//     isStained: false,
//     isAdminApproved: false,
//     isClientApproved: false,
//     remake_reason: "",
//     is_discounted: false,
//     subtotal: 500,
//     urgencyFee: 50,
//     finalBill: 550,
//   },
//   {
//     order_detail: [{ selectedTooth: [12, 32], type: "crown" }],
//     _id: "74g2b3c4d5e6f7h8i9j0k1l",
//     category: "Bridge",
//     patient_name: "Jane Smith",
//     clinic_name: "BrightCare Medical",
//     doctor_name: "Dr. Bob Smith",
//     prod_name: "Zirconia Bridge",
//     rx_date: "2025-11-20",
//     due_date: "2025-12-05",
//     doctor_instruction: "Match shade with adjacent teeth",
//     gender: "Female",
//     age: 38,
//     isUrgent: false,
//     is_remake: false,
//     designedPath: "/designs/order2.png",
//     designerId: "designer789",
//     deliveryId: "delivery101",
//     shade: "B1",
//     status: "Designing",
//     isAccepted: true,
//     isMilled: false,
//     isScanned: true,
//     isDesigned: true,
//     isDelivered: false,
//     isStained: false,
//     isAdminApproved: true,
//     isClientApproved: true,
//     remake_reason: "",
//     is_discounted: true,
//     subtotal: 800,
//     urgencyFee: 0,
//     finalBill: 720, // discounted
//   },
//   {
//     order_detail: [{ selectedTooth: [3], type: "implant" }],
//     _id: "84h3c4d5e6f7i8j9k0l1m2n",
//     category: "Implant",
//     patient_name: "Michael Brown",
//     clinic_name: "Global Health Partners",
//     doctor_name: "Dr. Clara Lee",
//     prod_name: "Titanium Implant",
//     rx_date: "2025-10-10",
//     due_date: "2025-11-01",
//     doctor_instruction: "Check gum healing before placement",
//     gender: "Male",
//     age: 52,
//     isUrgent: false,
//     is_remake: true,
//     designedPath: "/designs/order3.png",
//     designerId: "designer456",
//     deliveryId: "delivery789",
//     shade: "C3",
//     status: "Completed",
//     isAccepted: true,
//     isMilled: true,
//     isScanned: true,
//     isDesigned: true,
//     isDelivered: false,
//     isStained: true,
//     isAdminApproved: true,
//     isClientApproved: true,
//     remake_reason: "Initial implant size mismatch",
//     is_discounted: false,
//     subtotal: 1500,
//     urgencyFee: 0,
//     finalBill: 1500,
//   },
// ];
